import { EmojiOption } from '../types';

export const emojiOptions: EmojiOption[] = [
  { emoji: '🏖️', keywords: ['beach', 'vacation', 'sea', 'sun', 'sand'] },
  { emoji: '🏞️', keywords: ['nature', 'landscape', 'mountain', 'park'] },
  { emoji: '🏙️', keywords: ['city', 'downtown', 'urban', 'skyline'] },
  { emoji: '🏰', keywords: ['castle', 'landmark', 'historic', 'building'] },
  { emoji: '🏯', keywords: ['japanese castle', 'landmark', 'japan', 'historic'] },
  { emoji: '⛺', keywords: ['tent', 'camping', 'outdoor', 'nature'] },
  { emoji: '🏨', keywords: ['hotel', 'accommodation', 'stay'] },
  { emoji: '🏛️', keywords: ['museum', 'art', 'history', 'architecture'] },
  { emoji: '🏝️', keywords: ['island', 'tropical', 'beach', 'ocean'] },
  { emoji: '⛰️', keywords: ['mountain', 'hill', 'hiking', 'climbing'] },
  { emoji: '🏔️', keywords: ['snow mountain', 'ski', 'winter', 'snow'] },
  { emoji: '🌋', keywords: ['volcano', 'mountain', 'eruption', 'lava'] },
  { emoji: '🌄', keywords: ['sunrise', 'morning', 'dawn', 'day'] },
  { emoji: '🌅', keywords: ['sunset', 'evening', 'dusk'] },
  { emoji: '🌃', keywords: ['night', 'stars', 'city', 'evening'] },
  { emoji: '🌉', keywords: ['bridge', 'night', 'river', 'city'] },
  { emoji: '🌁', keywords: ['fog', 'mist', 'foggy', 'weather'] },
  { emoji: '🛣️', keywords: ['road', 'highway', 'drive', 'journey'] },
  { emoji: '🛤️', keywords: ['railway', 'train', 'transportation'] },
  { emoji: '🚆', keywords: ['train', 'transportation', 'travel'] },
  { emoji: '✈️', keywords: ['airplane', 'flight', 'travel', 'airport'] },
  { emoji: '🚢', keywords: ['ship', 'cruise', 'boat', 'sea'] },
  { emoji: '🚗', keywords: ['car', 'drive', 'road trip', 'transportation'] },
  { emoji: '🚲', keywords: ['bicycle', 'bike', 'cycling', 'transportation'] },
  { emoji: '🚶', keywords: ['walking', 'hike', 'tour', 'stroll'] },
  { emoji: '🏊', keywords: ['swimming', 'pool', 'water', 'beach'] },
  { emoji: '🧗', keywords: ['climbing', 'adventure', 'mountain'] },
  { emoji: '🏄', keywords: ['surfing', 'beach', 'ocean', 'water'] },
  { emoji: '🍽️', keywords: ['restaurant', 'food', 'dining', 'meal'] },
  { emoji: '🥂', keywords: ['drinks', 'cheers', 'celebration', 'bar'] },
  { emoji: '🎭', keywords: ['theater', 'performance', 'arts', 'show'] },
  { emoji: '🎬', keywords: ['movie', 'cinema', 'film', 'entertainment'] },
  { emoji: '🎨', keywords: ['art', 'museum', 'painting', 'gallery'] },
  { emoji: '📸', keywords: ['photography', 'camera', 'photo', 'picture'] },
  { emoji: '🎪', keywords: ['circus', 'carnival', 'festival', 'entertainment'] },
  { emoji: '🛍️', keywords: ['shopping', 'store', 'mall', 'market'] },
  { emoji: '⛪', keywords: ['church', 'religious', 'building', 'landmark'] },
  { emoji: '🕌', keywords: ['mosque', 'religious', 'building', 'landmark'] },
  { emoji: '🕍', keywords: ['synagogue', 'religious', 'building', 'landmark'] },
  { emoji: '🏬', keywords: ['department store', 'shopping', 'mall'] },
  { emoji: '🏟️', keywords: ['stadium', 'sports', 'event', 'game'] },
  { emoji: '🌲', keywords: ['tree', 'forest', 'nature', 'park'] },
  { emoji: '🌴', keywords: ['palm tree', 'tropical', 'beach', 'island'] },
  { emoji: '🌵', keywords: ['cactus', 'desert', 'dry', 'hot'] },
  { emoji: '🌊', keywords: ['wave', 'ocean', 'sea', 'water'] },
  { emoji: '🦈', keywords: ['shark', 'ocean', 'marine life', 'sea'] },
  { emoji: '🐬', keywords: ['dolphin', 'ocean', 'marine life', 'sea'] },
  { emoji: '🦁', keywords: ['lion', 'safari', 'animal', 'wildlife'] },
  { emoji: '🍎', keywords: ['apple', 'fruit', 'food', 'orchard'] },
  { emoji: '🍇', keywords: ['grapes', 'vineyard', 'wine', 'fruit'] },
  { emoji: '🍺', keywords: ['beer', 'brewery', 'drink', 'pub'] },
  { emoji: '☕', keywords: ['coffee', 'cafe', 'drink', 'morning'] },
  { emoji: '🎫', keywords: ['ticket', 'admission', 'event', 'entry'] },
  { emoji: '🗿', keywords: ['statue', 'monument', 'landmark', 'historic'] },
  { emoji: '💰', keywords: ['money', 'currency', 'shopping', 'budget'] },
  { emoji: '📞', keywords: ['phone', 'call', 'contact', 'reservation'] },
  { emoji: '📅', keywords: ['calendar', 'date', 'schedule', 'planning'] },
  { emoji: '⏰', keywords: ['alarm', 'time', 'wake up', 'schedule'] },
  { emoji: '🔍', keywords: ['search', 'find', 'explore', 'discover'] },
  { emoji: '🗺️', keywords: ['map', 'navigation', 'directions', 'location'] },
  { emoji: '📝', keywords: ['notes', 'memo', 'write', 'remember'] },
  { emoji: '📷', keywords: ['camera', 'photo', 'picture', 'memory'] },
  { emoji: '🔒', keywords: ['lock', 'security', 'safe', 'belongings'] },
  { emoji: '🧳', keywords: ['luggage', 'suitcase', 'packing', 'travel'] },
];